### ISSUE TITLE
Metric for SSN submitted is not working

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/dashboard#255]
The Metric based on the SSN submitted flag is not working as expected on the SM dashboard. 

When a user submits their SSN the flag updates appropriately but the count is not increasing on the SM dashboard as viewed by CCC users.

**Comment by FrogGirl1123** [comment]
@abhinavjonnada82 @mnataraj92 Could you please check your code/the participants table to see if the flags for the 4-digit and full social security are being populated.  The metrics are not matching what Michelle is seeing in the dashboard.  We're guessing either there is something wrong with the derivation of the metrics or the SS completion flag is being stored in the SS table instead of the participants table.  Please make this a high priority.

**Comment by mnataraj92** [comment]
@FrogGirl1123 @abhinavjonnada82  What I have for Marshfield in the daily metrics matches the dashboard (no SSN given for anyone). For SH, I have that there's 1 person with full SSN given but the dashboard shows no SSN given for anyone. For HP, I have that there's 1 person with full SSN given but the dashboard shows no SSN given for anyone. I checked what I'm getting on BQ, and what I'm getting matches what's on BQ.

**Comment by FrogGirl1123** [comment]
@abhinavjonnada82 please check your SSN metrics, it looks like it's not catching the SSN given flag.

**Comment by abhinavjonnada82** [comment]
@FrogGirl1123 @mnataraj92 released a fix and needs thorough testing before stage or prod deployment.

**Comment by abhinavjonnada82** [comment]
the SSN pie chart shows 
3 - partial SSN
2 - full SSN 
I believe  2 half & 2 full SSN were added as test data, the extra half is a previous entry
<img width="905" alt="Screen Shot 2021-12-09 at 1 30 32 PM" src="https://user-images.githubusercontent.com/30497847/145454828-8dbfff0b-57fc-4167-a05a-9ad1b05e9b1c.png">
