### ISSUE TITLE
Participant Lookup for email case sensitive?

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#404]
In the Participant Lookup, is the search on the Email case-sensitive? NORC reports this experience:

This issue has come up before when we were searching for a duplicate participant record. In the participant’s Verified account (Connect ID 4969757122), the participant capitalized the 1st letter of their email address. In their Duplicate account (Connect ID 2936376212), the participant did not capitalize the 1st letter of their email address. When we search by the participant’s email address, we only find one record.
Michelle tried and found the same thing... whether I search with the 1st letter capitalized or not, it always returns only the record where it is NOT capitalized.

Can the email search not be case-sensitive?

**Comment by robertsamm** [comment]
For this issue I believe we found out the issue was not with case sensitivity of the email. It had to do with the way we were storing the email address. I believe Tony fixed this a long time ago and pushed the solution to prod and also went back into the emails that were already stored and fixed those so they are searchable. @anthonypetersen can you please confirm so that we can close this issue out?
