### ISSUE TITLE
Consent signature and time stamp is wrong

### ISSUE THREAD

**Issue by robertsamm** [episphere/dashboard#56]
Can you fix the timestamp and signature on the downloaded consent form obtained in the participant summary page?

Currently it shows the participants last name as abbreviated, both first and last name should be spelled out in full. The timestamp also shows the time the consent was downloaded from the page and not the timestamp of consent. Example below.

![image](https://user-images.githubusercontent.com/67074735/115415593-089bf580-a1c5-11eb-99ce-3b34496aa6e0.png)
![image](https://user-images.githubusercontent.com/67074735/115415699-1fdae300-a1c5-11eb-9e89-e94b17e6616e.png)

**Comment by robertsamm** [comment]
@FrogGirl1123 @mnataraj92

**Comment by abhinavjonnada82** [comment]
Consented & HIPAA dates used instead of current timestamp.
<img width="1742" alt="Screen Shot 2021-06-05 at 3 58 26 PM" src="https://user-images.githubusercontent.com/30497847/120903880-df211700-c616-11eb-8cf4-1c5f2097afe8.png">
<img width="1125" alt="Screen Shot 2021-06-05 at 3 59 06 PM" src="https://user-images.githubusercontent.com/30497847/120903902-f7913180-c616-11eb-9e6c-f2800fd3817a.png">

**Comment by brotzmanmj** [comment]
Abhinav, did you fix this for all the agreements: Consent, HIPAA, HIPAA revocation form, and Data Destruction Form?

**Comment by abhinavjonnada82** [comment]
yes i did

**Comment by abhinavjonnada82** [comment]
> Abhinav, did you fix this for all the agreements: Consent, HIPAA, HIPAA revocation form, and Data Destruction Form?

yes i did
